export const materials = [
  {
    title: "Kinh tế vi mô – Cung, cầu và thị trường",
    subject: "Kinh tế vi mô",
    type: "lesson",
    duration: 18,
    description:
      "Hiểu cách cung, cầu và giá cả cùng quyết định trạng thái cân bằng của thị trường.",
    body: "Cầu là lượng hàng hóa người tiêu dùng sẵn lòng và có khả năng mua tại các mức giá khác nhau. Khi giá tăng, lượng cầu thường giảm, nếu các yếu tố khác không đổi.\n\nCung là lượng hàng hóa người bán sẵn lòng và có khả năng bán. Giá tăng thường làm lượng cung tăng.\n\nĐiểm cân bằng xuất hiện khi lượng cung bằng lượng cầu. Nếu giá cao hơn giá cân bằng, thị trường dư cung; nếu thấp hơn, thị trường thiếu hụt.\n\nVí dụ: Qd = 100 − 2P; Qs = 20 + 2P. Giải Qd = Qs cho P = 20 và Q = 60.\n\nBài tập: Với Qd = 120 − 3P và Qs = 20 + 2P, hãy tìm giá và sản lượng cân bằng. Đáp án: P = 20, Q = 60.",
  },
  {
    title: "Marketing căn bản – Hiểu khách hàng",
    subject: "Marketing căn bản",
    type: "lesson",
    duration: 22,
    description:
      "Khám phá mô hình 4P, phân khúc thị trường và định vị thương hiệu.",
    body: "Marketing tạo ra, truyền đạt và trao đổi giá trị cho khách hàng. Mô hình 4P gồm Product (sản phẩm), Price (giá), Place (phân phối), Promotion (xúc tiến).\n\nSTP gồm Segmentation (phân khúc), Targeting (chọn thị trường mục tiêu), Positioning (định vị). Phân khúc có thể theo địa lý, nhân khẩu học, tâm lý hoặc hành vi.\n\nVí dụ: Một quán cà phê gần trường chọn sinh viên làm khách hàng mục tiêu, định vị là không gian học tập yên tĩnh với giá vừa túi tiền.\n\nBài tập: Lập bảng 4P cho một sản phẩm bạn yêu thích và giải thích giá trị khác biệt của sản phẩm.",
  },
  {
    title: "Quản trị học – Lập kế hoạch hiệu quả",
    subject: "Quản trị học",
    type: "lesson",
    duration: 16,
    description: "Bốn chức năng quản trị và cách thiết lập mục tiêu SMART.",
    body: "Quản trị bao gồm lập kế hoạch, tổ chức, lãnh đạo và kiểm soát. Lập kế hoạch xác định mục tiêu và hành động; tổ chức phân bổ nguồn lực; lãnh đạo thúc đẩy con người; kiểm soát đo kết quả và điều chỉnh.\n\nMục tiêu SMART: Specific (cụ thể), Measurable (đo được), Achievable (khả thi), Relevant (phù hợp), Time-bound (có thời hạn).\n\nVí dụ: Hoàn thành 30 câu hỏi ôn tập Kinh tế vi mô trước 20 giờ ngày thứ Sáu, đạt ít nhất 80% câu đúng.\n\nBài tập: Viết mục tiêu SMART cho học kỳ tới, xác định nguồn lực và cách theo dõi tiến độ.",
  },
  {
    title: "Bộ câu hỏi ôn tập Kinh tế vi mô",
    subject: "Kinh tế vi mô",
    type: "document",
    duration: 0,
    description: "Câu hỏi tự luận và bài tập tính toán có hướng dẫn giải.",
    body: "1. Phân biệt sự thay đổi lượng cầu và sự thay đổi cầu.\n2. Những yếu tố nào làm đường cung dịch chuyển?\n3. Cho Qd = 100 − 2P và Qs = 20 + 2P, tìm cân bằng.\n4. Khi thu nhập tăng, cầu hàng hóa thông thường thay đổi thế nào?\n\nHướng dẫn: Lượng cầu thay đổi do giá chính hàng hóa; cầu thay đổi do thu nhập, thị hiếu, giá hàng liên quan và kỳ vọng. Chi phí đầu vào, công nghệ, thuế và số nhà sản xuất ảnh hưởng đến cung. Câu 3: P = 20, Q = 60. Câu 4: Cầu thường tăng.",
  },
  {
    title: "Đề tự kiểm tra Marketing căn bản",
    subject: "Marketing căn bản",
    type: "exam",
    duration: 15,
    description: "Ôn tập 4P, STP và hành vi người tiêu dùng.",
    body: "1. Hãy kể tên 4 thành phần của marketing mix.\n2. STP là gì?\n3. Phân biệt phân khúc và lựa chọn thị trường mục tiêu.\n4. Đề xuất cách định vị cho một sản phẩm dành cho sinh viên.\n\nĐáp án gợi ý: Product, Price, Place, Promotion. STP là phân khúc, chọn mục tiêu, định vị. Phân khúc chia thị trường thành nhóm; lựa chọn mục tiêu quyết định nhóm cần phục vụ.",
  },
  {
    title: "Tiếng Anh – Everyday campus vocabulary",
    subject: "Tiếng Anh",
    type: "document",
    duration: 0,
    description:
      "Từ vựng thông dụng và bài luyện tập trong môi trường đại học.",
    body: "Assignment: bài tập được giao. Deadline: hạn chót. Scholarship: học bổng. Lecture: bài giảng. Semester: học kỳ.\n\nExample: I need to finish my assignment before the deadline.\n\nPractice: Write five sentences about your weekly study schedule using these words.",
  },
];
export const questionBank = [
  [
    "Kinh tế vi mô",
    "Khi giá hàng hóa tăng, các yếu tố khác không đổi, lượng cung thường thế nào?",
    ["Tăng", "Giảm", "Không đổi", "Bằng không"],
    0,
    "Giá cao hơn tạo động lực cho nhà sản xuất cung ứng nhiều hơn.",
    "CUNG",
  ],
  [
    "Kinh tế vi mô",
    "Điểm cân bằng thị trường xuất hiện khi nào?",
    [
      "Lượng cung bằng lượng cầu",
      "Giá bằng không",
      "Cầu luôn lớn hơn cung",
      "Không có người bán",
    ],
    0,
    "Cân bằng là nơi đường cung và đường cầu giao nhau.",
    "CAN BANG",
  ],
  [
    "Kinh tế vi mô",
    "Qd = 100 − 2P, Qs = 20 + 2P. Giá cân bằng là bao nhiêu?",
    ["20", "10", "40", "60"],
    0,
    "100 − 2P = 20 + 2P, suy ra 4P = 80 và P = 20.",
    "GIA",
  ],
  [
    "Kinh tế vi mô",
    "Khi giá cao hơn giá cân bằng, thị trường thường có tình trạng nào?",
    ["Dư cung", "Thiếu hụt", "Cân bằng", "Không có cung"],
    0,
    "Giá cao khiến người bán cung nhiều hơn lượng người mua cần.",
    "DU CUNG",
  ],
  [
    "Kinh tế vi mô",
    "Giá của chính hàng hóa thay đổi gây ra điều gì?",
    [
      "Di chuyển dọc đường cầu",
      "Luôn dịch chuyển cả đường cầu",
      "Thu nhập tăng",
      "Thị hiếu thay đổi",
    ],
    0,
    "Giá chính hàng hóa làm lượng cầu thay đổi dọc theo đường cầu.",
    "CAU",
  ],
  [
    "Kinh tế vi mô",
    "Chi phí đầu vào giảm thường làm đường cung dịch chuyển về đâu?",
    ["Sang phải", "Sang trái", "Không thay đổi", "Thẳng đứng"],
    0,
    "Chi phí thấp hơn cho phép cung nhiều hơn tại mỗi mức giá.",
    "CHI PHI",
  ],
  [
    "Marketing căn bản",
    "4P gồm những thành phần nào?",
    [
      "Sản phẩm, giá, phân phối, xúc tiến",
      "Con người, lợi nhuận, kế hoạch, quy trình",
      "Giá, lương, vốn, thuế",
      "Chỉ sản phẩm và giá",
    ],
    0,
    "Product, Price, Place và Promotion là bốn thành phần 4P.",
    "MARKETING",
  ],
  [
    "Marketing căn bản",
    "STP có bước đầu tiên là gì?",
    ["Phân khúc thị trường", "Định giá", "Quảng cáo", "Bán hàng"],
    0,
    "Segmentation đứng đầu quy trình STP.",
    "PHAN KHUC",
  ],
  [
    "Marketing căn bản",
    "Định vị thương hiệu nhằm mục đích gì?",
    [
      "Tạo vị trí khác biệt trong tâm trí khách hàng",
      "Giảm mọi chi phí về không",
      "Bỏ qua đối thủ",
      "Chỉ tăng số nhân viên",
    ],
    0,
    "Định vị xác lập giá trị khác biệt có ý nghĩa với nhóm mục tiêu.",
    "DINH VI",
  ],
  [
    "Marketing căn bản",
    "Kênh phân phối thuộc thành phần nào của 4P?",
    ["Place", "Price", "Product", "Promotion"],
    0,
    "Place là phân phối, giúp sản phẩm đến với khách hàng.",
    "PLACE",
  ],
  [
    "Marketing căn bản",
    "Chọn nhóm khách hàng cần phục vụ là bước nào của STP?",
    ["Targeting", "Segmentation", "Positioning", "Promotion"],
    0,
    "Targeting là lựa chọn thị trường mục tiêu.",
    "TARGET",
  ],
  [
    "Quản trị học",
    "Chức năng nào xác định mục tiêu và hành động?",
    ["Lập kế hoạch", "Kiểm soát", "Lãnh đạo", "Báo cáo"],
    0,
    "Lập kế hoạch xác định đích đến và cách thực hiện.",
    "KE HOACH",
  ],
  [
    "Quản trị học",
    "Chữ M trong SMART có nghĩa là gì?",
    ["Đo lường được", "Nhanh nhất", "Nhiều nhất", "Dễ nhất"],
    0,
    "Measurable: mục tiêu có chỉ số để đo kết quả.",
    "SMART",
  ],
  [
    "Quản trị học",
    "Kiểm soát trong quản trị bao gồm việc nào?",
    [
      "Đo kết quả và điều chỉnh",
      "Chỉ giao việc",
      "Chỉ tuyển dụng",
      "Bỏ qua sai lệch",
    ],
    0,
    "Kiểm soát đối chiếu kết quả với mục tiêu để điều chỉnh.",
    "KIEM SOAT",
  ],
  [
    "Quản trị học",
    "Phân bổ nguồn lực thuộc chức năng nào?",
    ["Tổ chức", "Lãnh đạo", "Kiểm soát", "Định giá"],
    0,
    "Tổ chức bố trí con người và nguồn lực phục vụ mục tiêu.",
    "TO CHUC",
  ],
  [
    "Quản trị học",
    "Mục tiêu SMART cần có yếu tố thời gian nào?",
    ["Thời hạn rõ ràng", "Không có hạn", "Chỉ giờ bắt đầu", "Chỉ ngày nghỉ"],
    0,
    "Time-bound giúp mục tiêu có thời hạn hoàn thành.",
    "THOI HAN",
  ],
  [
    "Tiếng Anh",
    "“Deadline” có nghĩa là gì?",
    ["Hạn chót", "Học bổng", "Học kỳ", "Thư viện"],
    0,
    "Deadline là thời điểm cuối cùng để hoàn thành công việc.",
    "DEADLINE",
  ],
  [
    "Tiếng Anh",
    "Từ nào có nghĩa là “học bổng”?",
    ["Scholarship", "Semester", "Lecture", "Assignment"],
    0,
    "Scholarship là học bổng.",
    "SCHOLARSHIP",
  ],
  [
    "Tiếng Anh",
    "“Assignment” có nghĩa là gì?",
    ["Bài tập được giao", "Giảng đường", "Kỳ thi", "Giáo viên"],
    0,
    "Assignment là bài tập hoặc nhiệm vụ được giao.",
    "ASSIGNMENT",
  ],
  [
    "Tiếng Anh",
    "“Semester” có nghĩa là gì?",
    ["Học kỳ", "Học phí", "Hạn chót", "Phòng học"],
    0,
    "Semester là một học kỳ.",
    "SEMESTER",
  ],
  [
    "Tiếng Anh",
    "Từ nào có nghĩa là “bài giảng”?",
    ["Lecture", "Library", "Break", "Campus"],
    0,
    "Lecture là bài giảng.",
    "LECTURE",
  ],
];
export const gameModes = [
  {
    id: "quiz",
    name: "Quiz Challenge",
    icon: "🏆",
    color: "peach",
    description: "Trả lời câu hỏi trắc nghiệm theo chủ đề môn học.",
  },
  {
    id: "flashcard",
    name: "Flashcard Battle",
    icon: "🗂️",
    color: "mint",
    description: "Lật thẻ ôn kiến thức, rồi thử sức ghi nhớ.",
  },
  {
    id: "puzzle",
    name: "Puzzle Kiến Thức",
    icon: "🧩",
    color: "pink",
    description: "Ghép mảnh để hoàn thiện bức tranh kiến thức.",
  },
  {
    id: "speed",
    name: "Đấu Trường Tốc Độ",
    icon: "⏱️",
    color: "lavender",
    description: "Trả lời nhanh, tăng phản xạ và ghi điểm.",
  },
  {
    id: "crossword",
    name: "Game Ô chữ",
    icon: "🔤",
    color: "sky",
    description: "Giải ô chữ với những thuật ngữ quan trọng.",
  },
  {
    id: "daily",
    name: "Thử thách hằng ngày",
    icon: "📅",
    color: "yellow",
    description: "Mỗi ngày một thử thách kiến thức mới.",
  },
  {
    id: "race",
    name: "Đường Đua Học Tập",
    icon: "🏎️",
    color: "peach",
    description: "Vượt từng chặng bằng câu trả lời chính xác.",
  },
  {
    id: "subject",
    name: "Game theo môn học",
    icon: "📚",
    color: "mint",
    description: "Chọn môn yêu thích và khám phá kiến thức.",
  },
];
export const rewardSeed = [
  ["Móc khóa Smart", "🔑", 450, "souvenir", 20],
  ["Sticker set Smart", "🌈", 300, "souvenir", 30],
  ["Bình nước Smart", "🥤", 1200, "study", 15],
  ["Sổ tay Smart", "📒", 1000, "study", 20],
  ["Túi tote Smart", "👜", 1500, "souvenir", 12],
  ["Áo thun Smart", "👕", 2500, "souvenir", 10],
  ["Nón Smart", "🧢", 1200, "souvenir", 12],
  ["Bút Smart", "🖊️", 600, "study", 35],
];
